// Generated by scripts/sync-server-plugins.ts from convex/lib — do not edit.
// Change the original and run `bun run sync:plugins` (the package's build
// does it for you). Imported in type position only; none of it ships.

/**
 * One number: which generation of the client/server contract this deployment
 * speaks.
 *
 * The published client infers its types from copies of the server plugins
 * (`packages/react/src/server-plugins/`, written by `scripts/sync-server-plugins.ts`).
 * That works exactly as long as the deployment is running the same generation
 * of those plugins. When it isn't, nothing complains: the types keep compiling
 * and describe a server that no longer exists — `signIn.solana()` type-checks
 * against a signature the deployment stopped offering. The compiler is on the
 * wrong side of the failure, which is what makes it the bug report nobody can
 * explain.
 *
 * So the deployment says which generation it is (on `/aussieauth/status`,
 * which the card already calls) and the package compares it with the number
 * compiled into it. This file is copied into the package by the sync script,
 * so the two can't drift: bumping it here bumps it there on the next build,
 * and `sync:plugins --check` fails CI if someone forgets.
 *
 * **Bump this whenever a server plugin's request or response shape changes** —
 * a new required field, a renamed one, an endpoint that moves. Adding a plugin
 * or a purely additive optional field doesn't need it: an older client is still
 * correct about everything it knows.
 */
export const CONTRACT_GENERATION = 1;
