#!/usr/bin/env bun
/**
 * Copies the server plugins the package needs types for out of `convex/lib`.
 *
 * `packages/react/src/client.ts` builds its client plugins from
 * `ReturnType<typeof solana>` and friends, so it needs those declarations at
 * type-check time — but it can't import them from `convex/`, because the
 * published package has no Convex tree next to it. The copies under
 * `src/server-plugins/` are what stands in.
 *
 * They used to be kept in step by hand, with a test that compared the two
 * files byte for byte and went red when they drifted. That made every
 * server-plugin edit a two-file edit whose only reminder was a failing build.
 * This writes the second file instead.
 *
 *   bun run scripts/sync-server-plugins.ts           # write the copies
 *   bun run scripts/sync-server-plugins.ts --check   # fail if they're stale
 *
 * `--check` is what CI runs, so a commit that edits `convex/lib` without
 * regenerating is caught before it's published rather than after.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const SOURCE_DIR = join(root, "convex/lib");
export const TARGET_DIR = join(root, "packages/react/src/server-plugins");

/**
 * The plugins the client needs a type for. Everything else in `convex/lib`
 * either has no client half (`apps`, `methods`, `twoFactorGate`) or reaches
 * into Convex and so can't be copied at all (`notify`, `apple`).
 */
export const COPIED = ["accountNumber", "demo", "linking", "solana", "status"];

const BANNER = `// Generated by scripts/sync-server-plugins.ts from convex/lib — do not edit.
// Change the original and run \`bun run sync:plugins\` (the package's build
// does it for you). Imported in type position only; none of it ships.
`;

const generate = (source: string) => `${BANNER}\n${source}`;

/** What each copy should contain, keyed by filename. */
export const expected = async (): Promise<Map<string, string>> => {
  const out = new Map<string, string>();
  for (const name of COPIED) {
    const source = await readFile(join(SOURCE_DIR, `${name}.ts`), "utf8");
    out.set(`${name}.ts`, generate(source));
  }
  return out;
};

/** The copies that are missing, stale, or no longer have an original. */
export const stale = async (): Promise<string[]> => {
  const want = await expected();
  const found = (await readdir(TARGET_DIR).catch(() => [])).filter((f) => f.endsWith(".ts"));
  const problems = found.filter((f) => !want.has(f)).map((f) => `${f} (orphaned)`);

  for (const [file, content] of want) {
    const actual = await readFile(join(TARGET_DIR, file), "utf8").catch(() => null);
    if (actual === null) problems.push(`${file} (missing)`);
    else if (actual !== content) problems.push(`${file} (stale)`);
  }
  return problems;
};

if (import.meta.main) {
  const problems = await stale();

  if (process.argv.includes("--check")) {
    if (problems.length) {
      console.error(
        `Server-plugin copies are out of date:\n  ${problems.join("\n  ")}\n\n` +
          "Run `bun run sync:plugins` and commit the result.",
      );
      process.exit(1);
    }
    console.log(`Server-plugin copies are up to date (${COPIED.length} files).`);
  } else {
    for (const [file, content] of await expected()) {
      await writeFile(join(TARGET_DIR, file), content);
    }
    console.log(
      problems.length
        ? `Synced ${COPIED.length} server plugins — updated ${problems.length}.`
        : `Synced ${COPIED.length} server plugins — already current.`,
    );
  }
}
