/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as SetupAppleRouteImport } from './routes/setup/apple'
import { Route as SetupGoogleRouteImport } from './routes/setup/google'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAppleRoute = SetupAppleRouteImport.update({
  id: '/setup/apple',
  path: '/setup/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupGoogleRoute = SetupGoogleRouteImport.update({
  id: '/setup/google',
  path: '/setup/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/playground': typeof PlaygroundRoute
  '/sign-in': typeof SignInRoute
  '/docs/$': typeof DocsSplatRoute
  '/setup/apple': typeof SetupAppleRoute
  '/setup/google': typeof SetupGoogleRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/playground': typeof PlaygroundRoute
  '/sign-in': typeof SignInRoute
  '/docs/$': typeof DocsSplatRoute
  '/setup/apple': typeof SetupAppleRoute
  '/setup/google': typeof SetupGoogleRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/playground': typeof PlaygroundRoute
  '/sign-in': typeof SignInRoute
  '/docs/$': typeof DocsSplatRoute
  '/setup/apple': typeof SetupAppleRoute
  '/setup/google': typeof SetupGoogleRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/playground'
    | '/sign-in'
    | '/docs/$'
    | '/setup/apple'
    | '/setup/google'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/playground'
    | '/sign-in'
    | '/docs/$'
    | '/setup/apple'
    | '/setup/google'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/playground'
    | '/sign-in'
    | '/docs/$'
    | '/setup/apple'
    | '/setup/google'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SignInRoute: typeof SignInRoute
  DocsSplatRoute: typeof DocsSplatRoute
  SetupAppleRoute: typeof SetupAppleRoute
  SetupGoogleRoute: typeof SetupGoogleRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/apple': {
      id: '/setup/apple'
      path: '/setup/apple'
      fullPath: '/setup/apple'
      preLoaderRoute: typeof SetupAppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/google': {
      id: '/setup/google'
      path: '/setup/google'
      fullPath: '/setup/google'
      preLoaderRoute: typeof SetupGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  PlaygroundRoute: PlaygroundRoute,
  SignInRoute: SignInRoute,
  DocsSplatRoute: DocsSplatRoute,
  SetupAppleRoute: SetupAppleRoute,
  SetupGoogleRoute: SetupGoogleRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
